<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /* 
        
            finally() 方法
                - 返回一个Promise。在promise结束时，无论结果是fulfilled或者是rejected，都会执行指定的回调函数。这为在Promise是否成功完成后都需要执行的代码提供了一种方式。
                - finally接受不到参数，所以finally的回调函数不需要书写参数

                - finally返回值：
                    - 如果finally的回调函数没有返回一个promise对象
                        - 当成功状态的promise对象调用finally的时候，返回一个成功的promise对象，值为调用finally的promise对象的值
                        - 当失败状态的promise对象调用finally的时候，返回一个失败的promise对象，值为调用finally的promise对象的值
                        
                    - 如果finally的回调函数返回一个promise对象
                        - finally的回调函数返回的是一个成功的promise对象
                            - 如果是成功的promise对象调用的finally，则finally返回成功promise对象，值为调用finally回调函数的promise对象的值
                            - 如果是失败的promise对象调用的finally，则finally返回失败的promise对象，值为调用finally回调函数的promise对象的值
                        - finally的回调函数返回的是一个失败的promise对象
                            - 如果是成功的promise对象调用的finally，则finally返回失败promise对象，值为回调函数的返回的promise对象的值
                            - 如果是失败的promise对象调用的finally，则finally返回失败的promise对象，值为回调函数的返回的promise对象的值
                        - finally的回调函数返回的是一个未定义状态的的promise对象

        
        */

        const p1 = new Promise((resolve, reject) => {
            console.log("开始请求a。。。。");

            setTimeout(() => {
                try {
                    //模拟抛出错误（后边代码不再执行直接进入catch）
                    throw new Error("a数据请求失败")

                    //a请求成功
                    console.log("a数据请求成功");
                    //模拟请求回来的a数据
                    const dataA = [1, 2, 3, 4];
                    //调用成功回调
                    resolve(dataA);
                } catch (e) {
                    console.log(e);
                    //错误处理
                    reject(e);
                }
            }, 1000)

        })


        /* 
            简单总结：
                - 如果finally回调函数中没有返回任何的promise对象，则finally返回值和调用finally的promise对象一样
                - 如果finally回调函数中返回了promise对象
                    - 返回的是失败的，则无论是谁调用finally，finally都会返回失败
                    - 返回的是成功的，则调用finally的promise对象是什么，finally就返回什么
        
        */
        const re = p1.finally((data) => {
            return new Promise((resolve, reject) => {
                reject("1111")
            })
            console.log("data", data);
            console.log("finally调用");
        })

        console.log("re", re);
    </script>
</body>

</html>